### ISSUE TITLE
Can't start rails after upgrading rails 5.2.3 to 6.0

### ISSUE THREAD

**Issue by abigoroth** [influitive/apartment#617]
## Steps to reproduce
1. `rails app:update`
2. manually update rails gem from 5.2.3 to 6.0 in Gemfile
3. `bundle update`

## Expected behavior
Supposedly rails will start as usual.

## Actual behavior
/Users/ahmadyakobbinabaidullah/.asdf/installs/ruby/2.5.1/lib/ruby/gems/2.5.0/gems/actionpack-6.0.0/lib/action_dispatch/middleware/stack.rb:37:in `build': undefined method `new' for "Apartment::Reloader":String (NoMethodError)
Did you mean?  next

## System configuration
```
default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  # pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  pool: 220
  connect_timeout: 5
  read_timeout: 5
```

* Database: (Tell us what database and its version you use.)
psql (PostgreSQL) 9.6.2

* Apartment version:
apartment (0.24.3)

* Apartment config (in `config/initializers/apartment.rb` or so):
nothing yet.

  * `use_schemas`: (`true` or `false`)
nothing yet.

* Rails (or ActiveRecord) version:
Rails 6.0.0

* Ruby version:
ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-darwin17]

**Comment by mkhairi** [comment]
not support rails 6 yet. see https://github.com/influitive/apartment/issues/559

**Comment by ekampp** [comment]
@mkhairi , it says [right here](https://github.com/influitive/apartment/blob/development/apartment.gemspec#L22) that there is support for < 6.1. #559 is specifically about supporting Rails 6 multi-db. This error happens when simply starting a vanilla Rails 6 app.

**Comment by mkhairi** [comment]
owh, no public release yet for rails 6. need to install gem from github branch development.  otherwise bundler will install older version.

**Comment by ekampp** [comment]
@mkhairi, that is true. But it feels like this should have been caught in a test in the master branch since this happens with a vanilla rails 6 app. 

The fact that @abigoroth found this problem means that he's using the master branch (or at least an unreleased branch based on it). The < 6.1 gemspec constrain in the master branch seems incorrect.

Does anyone know where a potential test that should have caught this would be located?

**Comment by mkhairi** [comment]
@ekampp  seem like bundler install version 0.24.3 gemspec constraint on ```activerecord >= 3.1.2```. that mean he doesn't  point to any unreleased branch yet.
> * Apartment version:
>   apartment (0.24.3)
 
The correct way to test with rails 6 at this moment is, install from github branch development

```gem 'apartment', github: 'influitive/apartment', branch: 'development'```

**Comment by ekampp** [comment]
@mkhairi, I checked out the dev branch, and that solves this problem. 

However, the master branch does state that it supports Rails < 6.1, but in fact, it doesn't (see master branch gemspec). So that is perhaps something worth noting.

**Comment by jhoynerk** [comment]
Is there any idea of when there's going to be a new release (hopefully one that include support for rails 6)

**Comment by domininik** [comment]
Any updates from Apartment team? :)

**Comment by mjfrey** [comment]
Any update on a new release that supports Rails 6?

**Comment by joseramonc** [comment]
I can confirm my app is working as expected with `development` branch after upgrading to rails 6.

However, a new release that formally support rails 6 release would be very helpful.

Thanks!

**Comment by ashishbista** [comment]
`development` branch worked for me as well. A version with rails 6 support would be helpful.

**Comment by dwood-somniainc** [comment]
We need complete rails 6 support. Thanks!

**Comment by thisismydesign** [comment]
A dev answered recently in https://github.com/influitive/apartment/issues/559. There seem to be more activity here, but you should probably follow this other issue.
