### ISSUE TITLE
Rails 5.1.1 and ruby 2.4.0 issues

### ISSUE THREAD

**Issue by yannickbon** [influitive/apartment#432]
Hi all, quite new to programming in general so bear with me please :)
I tried getting Apartment to work on a brand new rails 5.1.1/ruby 2.4.0 install.
Got these errors:

/usr/local/opt/rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/actionpack-5.1.1/lib/action_dispatch/middleware/stack.rb:35:in `build': undefined method `new' for "Apartment::Elevators::Subdomain":String (NoMethodError)
Did you mean?  next

Could someone help figure out what could be the issue? 
Thx

**Comment by robotmay** [comment]
I came across this the other day. In the bottom of your Apartment initializer you probably have:

`Rails.application.config.middleware.use "Apartment::Elevators::Subdomain"`

Change it to (removing the quotes):

`Rails.application.config.middleware.use Apartment::Elevators::Subdomain`

Not sure why those lines have those classes as strings but that fixed it for me :)

**Comment by mikecmpbll** [comment]
fixed in #422 . i'll do a gem release in the next couple of weeks.

thanks for reporting!

**Comment by loybert** [comment]
might be worth mentioning this fix as readme-section `Upgrading to 2.0`

**Comment by guy-roberts** [comment]
Just stumbled on this issue.
